---
# handlers file for jenkins-agent
- name: Reload Systemd
  systemd:
    daemon_reload: yes
    name: "{{ jenkins_swarm_service_name }}"
    enabled: yes
    state: started
  when: ansible_service_mgr == "systemd"
  become: true

- name: Restart Swarm Client service
  service:
    name: "{{ jenkins_swarm_service_name }}"
    enabled: yes
    state: restarted
  become: true
